import type { Color } from '@/types'

export const textColorMap: Record<Color, string> = {
  primary: 'text-primary',
  secondary: 'text-secondary',
  accent: 'text-accent',
  'exhibition-a': 'text-exhibition-a',
  'exhibition-b': 'text-exhibition-b',
  info: 'text-info',
  success: 'text-success',
  error: 'text-error',
  warning: 'text-warning',
  white: 'text-white',
  black: 'text-black',
  red: 'text-red-500',
  orange: 'text-orange-500',
  amber: 'text-amber-500',
  yellow: 'text-yellow-500',
  lime: 'text-lime-500',
  green: 'text-green-500',
  emerald: 'text-emerald-500',
  teal: 'text-teal-500',
  cyan: 'text-cyan-500',
  sky: 'text-sky-500',
  blue: 'text-blue-500',
  indigo: 'text-indigo-500',
  violet: 'text-violet-500',
  purple: 'text-purple-500',
  fuchsia: 'text-fuchsia-500',
  pink: 'text-pink-500',
  rose: 'text-rose-500',
  gray: 'text-gray-500',
  neutral: 'text-neutral-500',
}

export const bgColorMap: Record<Color, string> = {
  primary: 'bg-primary',
  secondary: 'bg-secondary',
  accent: 'bg-accent',
  'exhibition-a': 'bg-exhibition-a',
  'exhibition-b': 'bg-exhibition-b',
  info: 'bg-info',
  success: 'bg-success',
  error: 'bg-error',
  warning: 'bg-warning',
  white: 'bg-white',
  black: 'bg-black',
  red: 'bg-red-500',
  orange: 'bg-orange-500',
  amber: 'bg-amber-500',
  yellow: 'bg-yellow-500',
  lime: 'bg-lime-500',
  green: 'bg-green-500',
  emerald: 'bg-emerald-500',
  teal: 'bg-teal-500',
  cyan: 'bg-cyan-500',
  sky: 'bg-sky-500',
  blue: 'bg-blue-500',
  indigo: 'bg-indigo-500',
  violet: 'bg-violet-500',
  purple: 'bg-purple-500',
  fuchsia: 'bg-fuchsia-500',
  pink: 'bg-pink-500',
  rose: 'bg-rose-500',
  gray: 'bg-gray-500',
  neutral: 'bg-neutral-500',
}

export const borderColorMap: Record<Color, string> = {
  primary: 'border-primary',
  secondary: 'border-secondary',
  accent: 'border-accent',
  'exhibition-a': 'border-exhibition-a',
  'exhibition-b': 'border-exhibition-b',
  info: 'border-info',
  success: 'border-success',
  error: 'border-error',
  warning: 'border-warning',
  white: 'border-white',
  black: 'border-black',
  red: 'border-red-500',
  orange: 'border-orange-500',
  amber: 'border-amber-500',
  yellow: 'border-yellow-500',
  lime: 'border-lime-500',
  green: 'border-green-500',
  emerald: 'border-emerald-500',
  teal: 'border-teal-500',
  cyan: 'border-cyan-500',
  sky: 'border-sky-500',
  blue: 'border-blue-500',
  indigo: 'border-indigo-500',
  violet: 'border-violet-500',
  purple: 'border-purple-500',
  fuchsia: 'border-fuchsia-500',
  pink: 'border-pink-500',
  rose: 'border-rose-500',
  gray: 'border-gray-500',
  neutral: 'border-neutral-500',
}
