import type { Color } from '@/types'

export const textColorMap: Record<Color, string> = {
  primary: 'text-primary',
  secondary: 'text-secondary',
  accent: 'text-accent',
  'exhibition-a': 'text-exhibition-a',
  'exhibition-b': 'text-exhibition-b',
  info: 'text-info',
  success: 'text-success',
  error: 'text-error',
  warning: 'text-warning',
  white: 'text-white',
  gray: 'text-gray-500',
  orange: 'text-orange-500',
  yellow: 'text-yellow-500',
  green: 'text-green-500',
  blue: 'text-blue-500',
  'gray-light': 'text-gray-300',
  'orange-light': 'text-orange-400',
  'yellow-light': 'text-yellow-400',
  'green-light': 'text-green-400',
  'blue-light': 'text-blue-400',
}

export const bgColorMap: Record<Color, string> = {
  primary: 'bg-primary',
  secondary: 'bg-secondary',
  accent: 'bg-accent',
  'exhibition-a': 'bg-exhibition-a',
  'exhibition-b': 'bg-exhibition-b',
  info: 'bg-info',
  success: 'bg-success',
  error: 'bg-error',
  warning: 'bg-warning',
  white: 'bg-white',
  gray: 'bg-gray-500',
  orange: 'bg-orange-500',
  yellow: 'bg-yellow-500',
  green: 'bg-green-500',
  blue: 'bg-blue-500',
  'gray-light': 'bg-gray-300',
  'orange-light': 'bg-orange-400',
  'yellow-light': 'bg-yellow-400',
  'green-light': 'bg-green-400',
  'blue-light': 'bg-blue-400',
}

export const borderColorMap: Record<Color, string> = {
  primary: 'border-primary',
  secondary: 'border-secondary',
  accent: 'border-accent',
  'exhibition-a': 'border-exhibition-a',
  'exhibition-b': 'border-exhibition-b',
  info: 'border-info',
  success: 'border-success',
  error: 'border-error',
  warning: 'border-warning',
  white: 'border-white',
  gray: 'border-gray-500',
  orange: 'border-orange-500',
  yellow: 'border-yellow-500',
  green: 'border-green-500',
  blue: 'border-blue-500',
  'gray-light': 'border-gray-300',
  'orange-light': 'border-orange-400',
  'yellow-light': 'border-yellow-400',
  'green-light': 'border-green-400',
  'blue-light': 'border-blue-400',
}
